### ISSUE TITLE
SRV/Redirect support?

### ISSUE THREAD

**Issue by ApexModder** [marchermans/serverpacklocator#4]
Initially adding this to my server, it worked fine but once I added an SRV record to my domain, to allow me to use the same IP/URL for a webpage that shows the list of installed mods, it broke SPL.

SPL now fails to connect on startup saying it can not download the server manifest JSON file.

Using the below SRV record you can navigate to https://play.apexstudios.dev/ and see installed mods and also connect to Minecraft server IP `play.apexstudios.dev` to play on the server [_whitelisted ofc_] but simply fails to connect after hitting the play button.

<details>

## Thrown exception

```log
[19:15:47] [pool-2-thread-1/ERROR]: Failed to download modpack from server: http://play.apexstudios.dev:1337
java.lang.IllegalStateException: Failed to download manifest
	at cpw.mods.forge.serverpacklocator.client.SimpleHttpClient.downloadManifest(SimpleHttpClient.java:73) ~[?:?]
	at cpw.mods.forge.serverpacklocator.client.SimpleHttpClient.connectAndDownload(SimpleHttpClient.java:50) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at cpw.mods.forge.serverpacklocator.client.SimpleHttpClient.lambda$new$1(SimpleHttpClient.java:45) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at cpw.mods.forge.serverpacklocator.client.SimpleHttpClient.downloadManifest(SimpleHttpClient.java:70) ~[?:?]
	... 7 more
[19:15:47] [main/INFO]: There was a problem with the connection, there will not be any server mods
```

## My SRV record setup

![image](https://user-images.githubusercontent.com/29412632/194398159-310e405b-0b9b-47da-83e4-23126db0f904.png)

</details>

**Comment by marchermans** [comment]
Interesting
I am not sure how I would fix this.

Does a server run on this?
And how does the client even loop up the SRV...

**Comment by marchermans** [comment]
We use url.openConnection. I am pretty sure that does not support srv records.

**Comment by ApexModder** [comment]
Closing due to staleness
